# Generated by Django 5.0.7 on 2024-07-20 20:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('max_num_vehicles', models.IntegerField()),
                ('num_vehicles', models.IntegerField(default=0)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='BlackListTokenAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingDailyIncomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num_inputs', models.BigIntegerField(default=0)),
                ('incomes', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('parking_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ParkingApp.parkinglot')),
            ],
        ),
        migrations.CreateModel(
            name='User_ParkingLots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_id', models.TextField(default='None', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkingApp.parkinglot')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleParkingHistorical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.TextField(max_length=6, null=True)),
                ('entry_time', models.DateTimeField(null=True)),
                ('parking_spot', models.IntegerField(null=True)),
                ('remarks', models.TextField(blank=True, max_length=300, null=True)),
                ('exit_time', models.DateTimeField(default=datetime.datetime(2024, 7, 20, 15, 57, 20, 776076))),
                ('hours', models.SmallIntegerField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parking_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ParkingApp.parkinglot')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleParkingRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.TextField(max_length=6, null=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('parking_spot', models.IntegerField(null=True)),
                ('remarks', models.TextField(blank=True, max_length=300, null=True)),
                ('parking_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ParkingApp.parkinglot')),
            ],
        ),
    ]
