# Generated by Django 5.0.7 on 2024-07-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingApp', '0002_parkinglot_vehicleparkinghistorical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdailyincomes',
            name='num_inputs',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicleparkinghistorical',
            name='hours',
            field=models.SmallIntegerField(),
        ),
    ]
