# Generated by Django 5.0.7 on 2024-07-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingApp', '0003_alter_parkingdailyincomes_num_inputs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='name',
            field=models.TextField(max_length=30, unique=True),
        ),
    ]
