# Generated by Django 5.0.7 on 2024-07-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingApp', '0005_user_parkinglots_relation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_parkinglots',
            name='relation_id',
            field=models.TextField(default='None', max_length=100, unique=True),
        ),
    ]
